### ISSUE TITLE
Incompatibility with sCrypt VSCode extension

### ISSUE THREAD

**Issue by MerlinB** [scrypt-sv/boilerplate#14]
All tests are running fine.

Using the context menu option "Compile to Bitcoin Script" fails though for some but not all of the example contracts.
The VSCode extension also lints these errors. For example in the demo contract:
![image](https://user-images.githubusercontent.com/7633719/94349777-1979f380-0048-11eb-9e1b-0182ae83dd1a.png)

**Comment by xhliu** [comment]
Upgraded to the latest version [0.4.0](https://marketplace.visualstudio.com/items?itemName=bsv-scrypt.sCrypt). Also make sure u have the latest boilerplate.

**Comment by MerlinB** [comment]
Thank you, working fine now. However, it seems debugging is broken in the new Version (see Slack).
