### ISSUE TITLE
Expected arguments (byte[]) but got (bytes)

### ISSUE THREAD

**Issue by MerlinB** [scrypt-sv/boilerplate#16]
`Constructor of contract ... expected arguments (byte[]) but got (bytes)` - This happens when entering bytes strings (`b'...'`) as input for `constructorParams` in `launch.json` and requiring a bytes string in the contract like this:
```
contract Test {
  bytes test;

  ...
}
```
When wrapped in Sha256 for example, it works fine.

**Comment by xhliu** [comment]
Did u pull the latest `boilerplate`?

**Comment by xhliu** [comment]
Fixed in IDE `0.4.2`.
